import type { Crew, Meetup } from './types'

export const MEETUPS: Meetup[] = [
  {
    id: 'm1',
    title: '반포 토요 새벽 5K',
    region: '반포·잠원',
    spot: '반포한강공원 달빛광장',
    dateLabel: '6/13 (토)',
    time: '06:00',
    distanceKm: 5,
    paceMin: 390,
    paceMax: 420,
    max: 12,
    members: ['새벽반장', '달리는수박', '한강갈매기', '러닝하는직장인', '슬로우조', '말랑발바닥', '아침형러너', '커피전에한바퀴'],
    host: '새벽반장',
    hostLevel: 'easy',
    beginnerOk: true,
    quiet: false,
    noDrop: true,
    night: false,
    certRequired: false,
    desc: '토요일 아침을 여는 반포 정기런입니다. 뒤처지는 사람 없이 다 같이 들어와요. 끝나고 광장에서 스트레칭하고 해산!',
    course: '달빛광장 → 반포대교 남단 → 동작대교 반환 → 달빛광장',
  },
  {
    id: 'm2',
    title: '여의도 10K 템포런',
    region: '여의도',
    spot: '여의나루역 2번 출구',
    dateLabel: '오늘 6/12 (금)',
    time: '20:00',
    distanceKm: 10,
    paceMin: 330,
    paceMax: 360,
    max: 10,
    members: ['페이스메이커K', '서브4도전', '한강치타', '금요질주', '바람의딸', '10K전문'],
    host: '페이스메이커K',
    hostLevel: 'tempo',
    beginnerOk: false,
    quiet: true,
    noDrop: false,
    night: true,
    certRequired: true,
    desc: '5:30~6:00 페이스로 꾸준히 미는 템포런. 조용히 달리는 걸 좋아하는 분들 환영. 야간이라 안전 모드 켜고 달립니다.',
    course: '여의나루 → 마포대교 → 원효대교 반환 → 여의나루',
  },
  {
    id: 'm3',
    title: '걷뛰 입문 클래스런',
    region: '석촌호수·잠실',
    spot: '석촌호수 동호 입구',
    dateLabel: '6/14 (일)',
    time: '09:00',
    distanceKm: 3,
    paceMin: 480,
    paceMax: 600,
    max: 15,
    members: ['호수러너', '오늘부터시작', '운동화새로삼', '작심삼일탈출', '천천히가요'],
    host: '호수러너',
    hostLevel: 'slow',
    beginnerOk: true,
    quiet: false,
    noDrop: true,
    night: false,
    certRequired: false,
    desc: '1분 뛰고 2분 걷는 걷뛰 루틴으로 3km를 함께해요. 러닝이 처음이어도, 숨차면 걸어도 아무도 눈치 안 줘요.',
    course: '석촌호수 동호 한 바퀴 반',
  },
  {
    id: 'm4',
    title: '잠원 조용한 저녁런',
    region: '반포·잠원',
    spot: '잠원한강공원 그늘막쉼터',
    dateLabel: '오늘 6/12 (금)',
    time: '21:00',
    distanceKm: 6,
    paceMin: 360,
    paceMax: 390,
    max: 8,
    members: ['묵묵히달림', '이어폰없이', '강북에서왔어요'],
    host: '묵묵히달림',
    hostLevel: 'tempo',
    beginnerOk: false,
    quiet: true,
    noDrop: false,
    night: true,
    certRequired: false,
    desc: '인사만 하고 조용히 각자 페이스로 달린 뒤 같은 지점에서 만나요. 말 거는 사람 없는 게 장점인 모임.',
    course: '잠원지구 → 한남대교 → 동호대교 반환',
  },
  {
    id: 'm5',
    title: '성수 카페런 — 뛰고 마시는 모임',
    region: '뚝섬·성수',
    spot: '서울숲 군마상 앞',
    dateLabel: '6/13 (토)',
    time: '10:00',
    distanceKm: 4,
    paceMin: 420,
    paceMax: 450,
    max: 10,
    members: ['뛰고라떼', '성수동주민', '브런치러너', '사진찍는러너', '수다금지없음', '주말이좋아'],
    host: '뛰고라떼',
    hostLevel: 'easy',
    beginnerOk: true,
    quiet: false,
    noDrop: true,
    night: false,
    certRequired: false,
    desc: '서울숲 가볍게 4km 돌고 성수 카페에서 커피 마시는 친목런. 러닝 반, 수다 반. 사진 많이 찍어요.',
    course: '서울숲 한 바퀴 → 성수 카페거리',
  },
  {
    id: 'm6',
    title: '강남 인터벌 훈련 클럽',
    region: '강남·양재천',
    spot: '탄천종합운동장 트랙',
    dateLabel: '6/13 (토)',
    time: '06:30',
    distanceKm: 8,
    paceMin: 270,
    paceMax: 300,
    max: 8,
    members: ['서브3가즈아', 'PB사냥꾼', '트랙중독', '400미터반복'],
    host: '서브3가즈아',
    hostLevel: 'racer',
    beginnerOk: false,
    quiet: true,
    noDrop: false,
    night: false,
    certRequired: true,
    desc: '400m x 10 인터벌. 가을 대회 대비 스피드 훈련입니다. 최근 10K 기록 50분 이내인 분들께 추천.',
    course: '탄천종합운동장 트랙 400m',
  },
  {
    id: 'm7',
    title: '여의도 노을 슬로우런',
    region: '여의도',
    spot: '여의도한강공원 물빛광장',
    dateLabel: '6/14 (일)',
    time: '19:30',
    distanceKm: 4,
    paceMin: 450,
    paceMax: 510,
    max: 12,
    members: ['노을수집가', '퇴근후한바퀴', '풍경이좋아', '느림의미학'],
    host: '노을수집가',
    hostLevel: 'slow',
    beginnerOk: true,
    quiet: false,
    noDrop: true,
    night: true,
    certRequired: false,
    desc: '노을 보면서 천천히 달리는 모임. 페이스 7:30~8:30, 힘들면 다 같이 걸어요. 야간 안전 모드 필수.',
    course: '물빛광장 → 샛강 합류부 → 서강대교 반환',
  },
  {
    id: 'm8',
    title: '잠실 하프 대비 LSD 16K',
    region: '석촌호수·잠실',
    spot: '잠실종합운동장 정문',
    dateLabel: '6/14 (일)',
    time: '06:00',
    distanceKm: 16,
    paceMin: 360,
    paceMax: 390,
    max: 10,
    members: ['하프준비중', '장거리체질', '일요일은LSD', '완주가목표', '급수담당'],
    host: '하프준비중',
    hostLevel: 'racer',
    beginnerOk: false,
    quiet: false,
    noDrop: true,
    night: false,
    certRequired: true,
    desc: '9월 하프마라톤 대비 장거리 지속주. 6:00~6:30 페이스로 끊지 않고 16km. 중간 급수 1회.',
    course: '잠실운동장 → 탄천 → 한강 합류 → 잠실대교 반환',
  },
]

export const CREW: Crew = {
  name: '반포 새벽런 클럽',
  region: '반포 · 잠원',
  intro: '화·목 새벽 6시, 토요일 아침 7시에 모이는 동네 정기런 크루. 페이스 안 봅니다, 출석만 봅니다.',
  members: [
    { name: '새벽반장', level: 'easy', attendRate: 95 },
    { name: '달리는수박', level: 'slow', attendRate: 88 },
    { name: '한강갈매기', level: 'tempo', attendRate: 82 },
    { name: '말랑발바닥', level: 'slow', attendRate: 76 },
    { name: '커피전에한바퀴', level: 'easy', attendRate: 71 },
    { name: '러닝하는직장인', level: 'easy', attendRate: 64 },
    { name: '아침형러너', level: 'tempo', attendRate: 58 },
  ],
  notices: [
    {
      id: 'n1',
      date: '6/11',
      text: '이번 토요런(6/13)은 달빛광장이 행사로 막혀서 세빛섬 앞 집결로 변경합니다! 06:50까지 와주세요.',
      pinned: true,
    },
    {
      id: 'n2',
      date: '6/9',
      text: '6월 출석왕 이벤트: 이번 달 정기런 80% 이상 출석 시 크루 양말 증정 🧦',
    },
    {
      id: 'n3',
      date: '6/5',
      text: '장마 시즌 우천 취소 공지는 당일 오전 5시에 올라갑니다. 알림 켜두세요.',
    },
  ],
  schedule: [
    {
      id: 's1',
      title: '화요 새벽런 5K',
      dayTime: '매주 화 06:00',
      spot: '반포대교 남단',
      pace: '6:30~7:00',
    },
    {
      id: 's2',
      title: '목요 걷뛰런 3K',
      dayTime: '매주 목 06:00',
      spot: '잠수교 북단',
      pace: '걷뛰 · 페이스 무관',
    },
    {
      id: 's3',
      title: '토요 정기런 7K',
      dayTime: '매주 토 07:00',
      spot: '세빛섬 앞 (6월 한정)',
      pace: '6:30~7:30',
    },
  ],
}
